[totp_viewer]
; TOTP Viewer Configuration
; 明文 otpauth 文件路径（可选）
otpauth = ./otpauth.txt

[decrypt]
; 解密程序路径（可以是相对路径或绝对路径）
; 如果配置了 decrypt ，优先使用加密文件
program = python3 decrypt.py
; program = python3 decrypt_key.py
; 加密数据文件路径
file = otpauth.enc